# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  database: booking_app_dev
  pool: 5432
  timeout: 5000
  user: vadivelankuppusamy
  password:
  host: localhost

test:
  adapter: postgresql
  database: booking_app_test
  pool: 5432
  timeout: 5000
  user: vadivelankuppusamy
  password:
  host: localhost

production:
  adapter: postgresql
  database: booking_app_prod
  pool: 5432
  timeout: 5000
  user: vadivelankuppusamy
  password:
  host: localhost

